# Generated by Django 3.2.6 on 2021-08-26 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=15, verbose_name='Product Code')),
                ('value', models.FloatField(verbose_name='Product Value')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('IN', 'In validation'), ('AP', 'Approved')], default=None, max_length=2, verbose_name='Status')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cpf')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ('cpf',),
            },
        ),
    ]
