# Generated by Django 3.2.6 on 2021-08-27 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='cpf', verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('IN', 'In Validation'), ('AP', 'Approved')], default='IN', max_length=2, verbose_name='Status'),
        ),
    ]
