# Generated by Django 3.2.6 on 2021-08-27 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210827_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='perc_cashback',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Percent Cashback apply'),
        ),
        migrations.AddField(
            model_name='sale',
            name='value_cashback',
            field=models.FloatField(default=0, editable=False, verbose_name='Value Cashback apply'),
        ),
    ]
