# Generated by Django 3.2.6 on 2021-08-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name',), 'verbose_name': 'Dealer', 'verbose_name_plural': 'Resellers'},
        ),
    ]
